### ISSUE TITLE
Please add your RFP and other documents as markdown with .md file extension

### ISSUE THREAD

**Issue by ourarash** [WorkOutLoudApp/documents#1]
Use this as a guide:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by personallyvnguyen** [comment]
Got it. Converted our RFP as a .md https://github.com/WorkOutLoudApp/documents/blob/main/request_for_proposal.md
